### ISSUE TITLE
Ensure we get any content length from the downloaded report before trying to parse it

### ISSUE THREAD

**Issue by Greenheart** [Klimatbyran/garbo#507]
Felet med Revolutionrace-rapporten för 2023/2024 verkar vara att den kraschar `nlm-ingestor`, som i sin tur kraschar för att `tika-server` (en underliggande dependecy för att konvertera dokument, bl.a. PDF:er) kraschar.

Oklart varför, men det kan vara värt att verifiera att vi får tillbaka någon faktisk data för rapporten, för att säkerställa oss om att servern inte returnerar en tom respons (0 bytes) för att den upptäcker att garbo är en bot och inte vill serva rapporten.

## TODO
- [ ] Add a check to the start of `nlmParsePDF` to only proceed with parsing a report if its buffer has any length. If its a completely empty report, then it's not strange that we get weird results. https://github.com/Klimatbyran/garbo/blob/60aec58df7cf69441434ad1c7123731ac089326a/src/workers/nlmParsePDF.ts#L24
- [ ] If we don't see a clear cause (like a blocked request with an empty response body), see if this report is easier to parse offline if we have it downloaded already.
- [ ] Finally, try if another parsing solution, like Docling (`feat/pdf2markdown`), could solve this.

Logg från worker:
![Uploading image.png…]()

Logg från nlm-ingestor (som viasr felet från tika-server):
![image](https://github.com/user-attachments/assets/62f78778-6ca0-4abb-aa7f-37188628cce5)
